### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by tkosamja** [OpenUserCSS/openusercss.org#71]
Whenever I try to log in, I get the following error: 

```
An error occurred within the application:
Cannot return null for non-nullable field Theme.ratings.
```

**Comment by DecentM** [comment]
Thanks for the report!

**Comment by DecentM** [comment]
I pushed an update with an attempt to work around this, without being able to reproduce it.  
This should be fixed with the refactor, but I wanted to fix this before that rolls out. Can you see if you're able to log in now?

**Comment by tkosamja** [comment]
Nope, still not working.

![screenshot from 2018-01-20 09-38-58](https://user-images.githubusercontent.com/26143003/35182075-c112fdfe-fdc5-11e7-9e4d-bf334a55b7cf.png)

**Comment by tkosamja** [comment]
Still not working. Any plans for it? I can't update my themes

**Comment by DecentM** [comment]
Sorry for the delay. In the currently live version of the site, the logic between the API and the site is very loose. Even if I did a quick fix for this issue, the next one would pop up almost immediately.  
I'm refactoring the site and adding tests as we speak, so that this can be fixed once and for all.

**Comment by DecentM** [comment]
This should be fixed with 1.0.0. I'll close this issue, but if it still persists for you, please let me know!
